export const pageShortcuts: Record<string, string> = {
	// page
	'k-pagination': 'fi p0 m0',
	'k-pagination-container': 'fi',
	'k-pagination-jumper': 'fi mx-1 text-ikun-tx-base',
	'k-pagination-sizes': 'mx-1',
	'k-pagination-pager-btn': 'w-full h-full fcc',
	'k-pagination-pager':
		'text-ikun-tx-base cursor-pointer list-none rounded fcc mx-1 px-1 box-border select-none !mt-0',
	'k-pagination-pager__sm': 'min-w-26px h-26px leading-26px text-sm',
	'k-pagination-pager__md': 'min-w-32px h-32px leading-32px',
	'k-pagination-pager__lg': 'min-w-38px h-38px leading-38px text-lg',
	'k-pagination-pager__active': 'text-ikun-main',
	'k-pagination-pager__hover': 'hover:text-ikun-main',
	'k-pagination-pager__bg__active': 'text-white bg-ikun-main',
	'k-pagination-pager__bg': 'bg-ikun-bg-gr',
	'k-pagination-pager__disabled': 'k-cur-disabled text-ikun-tx-gr',
	'k-pagination-jumper__disabled': 'k-cur-disabled text-ikun-tx-gr',
	'k-pagination-sizes__disabled': 'k-cur-disabled text-ikun-tx-gr',
	'k-pagination-total__disabled': 'k-cur-disabled text-ikun-tx-gr',
	'k-pagination-pager__disabled__bg': 'k-bg-disabled',
	'k-pagination-pager__disabled__bg__active': 'ikun:40:bg-ikun-main',
	'k-pagination-total': 'text-ikun-tx-base mx-1',
	'k-pagination-total__sm': 'h-26px leading-26px text-sm',
	'k-pagination-total__md': 'h-32px leading-32px',
	'k-pagination-total__lg': 'h-38px leading-38px text-lg',
	// dark
	'k-pagination-jumper__dark': 'dark:text-ikun-white',
	'k-pagination-total__dark': 'dark:text-ikun-white',
	'k-pagination-pager__dark': 'dark:text-ikun-white',
	'k-pagination-pager__dark__hover': 'dark:hover:(text-ikun-main [&>span]:text-ikun-main)',
	'k-pagination-pager__bg__dark': 'dark:(bg-ikun-dark-300 text-ikun-white)',
	'k-pagination-pager__disabled__bg__dark': 'dark:bg-ikun-dark-300',
	'k-pagination-pager__disabled__dark': 'dark:([&>span]:text-ikun-tx-gr)'
};
