export const skeletonShortcuts: Record<string, string> = {
	'k-skeleton': '',
	'k-skeleton-header': 'fsc w-full',
	'k-skeleton-content--sm': 'w-full pl-64px box-border',
	'k-skeleton-content--md': 'w-full pl-78px box-border',
	'k-skeleton-content--lg': 'w-full pl-96px box-border',
	'k-skeleton--active': 'animate-ikun-skeleton-loading k-skeleton-bg',
	'k-skeleton-title': 'rounded-4px',
	'k-skeleton-title-un--active': 'bg-ikun-light-700',
	'k-skeleton-title--sm': 'h-24px',
	'k-skeleton-title--md': 'h-32px',
	'k-skeleton-title--lg': 'h-40px',
	'k-skeleton-paragraph': 'pl-0',
	'k-skeleton-paragraph--item': 'bg-ikun-light-700 rounded-4px mt-16px list-none',
	'k-skeleton-paragraph--sm': 'h-24px',
	'k-skeleton-paragraph--md': 'h-32px',
	'k-skeleton-paragraph--lg': 'h-40px',
	'k-skeleton-avatar': 'bg-ikun-light-700 mr-16px',
	'k-skeleton-avatar-container--sm': 'h-48px mt-4px',
	'k-skeleton-avatar-container--md': 'h-62px ',
	'k-skeleton-avatar-container--lg': 'h-80px',
	'k-skeleton-avatar--sm': 'h-48px w-48px',
	'k-skeleton-avatar--md': 'h-62px w-62px',
	'k-skeleton-avatar--lg': 'h-80px w-80px',
	'k-skeleton-avatar--circle': 'rounded-full',
	'k-skeleton-avatar--round': 'rounded-4px',
	'k-skeleton-avatar--square': 'rounded-0',
	'k-skeleton-button': 'outline-none border-0',
	'k-skeleton-button--sm': 'h-24px w-48px',
	'k-skeleton-button--md': 'h-32px w-64px',
	'k-skeleton-button--lg': 'h-40px w-80px',
	'k-skeleton-button--block--sm': 'h-24px w-full',
	'k-skeleton-button--block--md': 'h-32px w-full',
	'k-skeleton-button--block--lg': 'h-40px w-full',
	'k-skeleton-button--circle--sm': 'h-24px w-24px rounded-full',
	'k-skeleton-button--circle--md': 'h-32px w-32px rounded-full',
	'k-skeleton-button--circle--lg': 'h-40px w-40px rounded-full',
	'k-skeleton-button--round': 'rounded-4px',
	'k-skeleton-button--square': 'rounded-0'
};
